# Generated by Django 6.0 on 2026-01-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_course_report_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='threads', to='forum.resource'),
        ),
    ]
